import os

from dotenv import load_dotenv


load_dotenv()

WEATHER_API_URL = os.getenv("WEATHER_API_URL")
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
GRPC_API_KEY = os.getenv("GRPC_API_KEY")
GRPC_PORT = os.getenv("GRPC_PORT")
GRPC_CLIENT_HOST = os.getenv("GRPC_CLIENT_HOST")
BACKEND_CONTAINER = os.getenv("BACKEND_CONTAINER")
MONGODB_USERNAME = os.getenv("MONGODB_USERNAME")
MONGODB_PASSWORD = os.getenv("MONGODB_PASSWORD")
MONGODB_PORT = os.getenv("MONGODB_PORT")
MONGODB_HOST = os.getenv("MONGODB_HOST")
DATABASE_NAME = os.getenv("DATABASE_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")
REQUEST_HOST = os.getenv("REQUEST_HOST")
REQUEST_PORT = os.getenv("REQUEST_PORT")
