# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\"\x1b\n\x0b\x43ityRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\x84\x01\n\x17\x43ityWeatherDataResponse\x12\x11\n\tcity_name\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x12\x1b\n\x13weather_description\x18\x03 \x01(\t\x12\x10\n\x08humidity\x18\x04 \x01(\x05\x12\x12\n\nwind_speed\x18\x05 \x01(\t2@\n\x0bWeatherData\x12\x31\n\x07Weather\x12\x0c.CityRequest\x1a\x18.CityWeatherDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CITYREQUEST']._serialized_start=17
  _globals['_CITYREQUEST']._serialized_end=44
  _globals['_CITYWEATHERDATARESPONSE']._serialized_start=47
  _globals['_CITYWEATHERDATARESPONSE']._serialized_end=179
  _globals['_WEATHERDATA']._serialized_start=181
  _globals['_WEATHERDATA']._serialized_end=245
# @@protoc_insertion_point(module_scope)
